{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "90df2c40-769c-4359-b97e-b19aabb7f924",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Introduce el nombre del Pokémon:  pikachu\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "**Nombre:** Pikachu\n",
      "**Imagen:** https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png\n",
      "**Peso:** 60 kg\n",
      "**Altura:** 4 m\n",
      "**Movimientos:**\n",
      " - mega-punch\n",
      " - pay-day\n",
      " - thunder-punch\n",
      " - slam\n",
      " - double-kick\n",
      " - mega-kick\n",
      " - headbutt\n",
      " - body-slam\n",
      " - take-down\n",
      " - double-edge\n",
      " - tail-whip\n",
      " - growl\n",
      " - surf\n",
      " - submission\n",
      " - counter\n",
      " - seismic-toss\n",
      " - strength\n",
      " - thunder-shock\n",
      " - thunderbolt\n",
      " - thunder-wave\n",
      " - thunder\n",
      " - dig\n",
      " - toxic\n",
      " - agility\n",
      " - quick-attack\n",
      " - rage\n",
      " - mimic\n",
      " - double-team\n",
      " - defense-curl\n",
      " - light-screen\n",
      " - reflect\n",
      " - bide\n",
      " - swift\n",
      " - skull-bash\n",
      " - flash\n",
      " - rest\n",
      " - substitute\n",
      " - thief\n",
      " - snore\n",
      " - curse\n",
      " - reversal\n",
      " - protect\n",
      " - sweet-kiss\n",
      " - mud-slap\n",
      " - zap-cannon\n",
      " - detect\n",
      " - endure\n",
      " - charm\n",
      " - rollout\n",
      " - swagger\n",
      " - spark\n",
      " - attract\n",
      " - sleep-talk\n",
      " - return\n",
      " - frustration\n",
      " - dynamic-punch\n",
      " - encore\n",
      " - iron-tail\n",
      " - hidden-power\n",
      " - rain-dance\n",
      " - rock-smash\n",
      " - uproar\n",
      " - facade\n",
      " - focus-punch\n",
      " - charge\n",
      " - helping-hand\n",
      " - brick-break\n",
      " - knock-off\n",
      " - endeavor\n",
      " - secret-power\n",
      " - fake-tears\n",
      " - signal-beam\n",
      " - covet\n",
      " - volt-tackle\n",
      " - calm-mind\n",
      " - shock-wave\n",
      " - natural-gift\n",
      " - feint\n",
      " - fling\n",
      " - magnet-rise\n",
      " - nasty-plot\n",
      " - discharge\n",
      " - captivate\n",
      " - grass-knot\n",
      " - charge-beam\n",
      " - electro-ball\n",
      " - round\n",
      " - echoed-voice\n",
      " - volt-switch\n",
      " - electroweb\n",
      " - wild-charge\n",
      " - disarming-voice\n",
      " - draining-kiss\n",
      " - play-rough\n",
      " - play-nice\n",
      " - confide\n",
      " - eerie-impulse\n",
      " - electric-terrain\n",
      " - nuzzle\n",
      " - laser-focus\n",
      " - rising-voltage\n",
      " - tera-blast\n",
      " - trailblaze\n",
      " - alluring-voice\n",
      " - upper-hand\n",
      "**Habilidades:**\n",
      " - static\n",
      " - lightning-rod\n",
      "**Tipos:**\n",
      " - electric\n",
      "Información del Pokémon guardada en el archivo 'pikachu' dentro de la carpeta 'pokedex'.\n"
     ]
    }
   ],
   "source": [
    "#Pokedex\n",
    "import requests\n",
    "import json\n",
    "import os\n",
    "\n",
    "# Crear la carpeta \"pokedex\" si no existe\n",
    "if not os.path.exists(\"pokedex\"):\n",
    "    os.makedirs(\"pokedex\")\n",
    "\n",
    "# Obtener el nombre del Pokémon del usuario\n",
    "nombre_pokemon = input(\"Introduce el nombre del Pokémon: \").lower()\n",
    "\n",
    "# Construir la URL de la API\n",
    "url = f\"https://pokeapi.co/api/v2/pokemon/{nombre_pokemon}\"\n",
    "\n",
    "# Obtener los datos del Pokémon de la API\n",
    "response = requests.get(url)\n",
    "\n",
    "# Comprobar si el Pokémon existe\n",
    "if response.status_code == 200:\n",
    "    # Obtener los datos del Pokémon\n",
    "    datos_pokemon = response.json()\n",
    "\n",
    "    # Obtener la imagen del Pokémon\n",
    "    imagen_pokemon = datos_pokemon[\"sprites\"][\"front_default\"]\n",
    "\n",
    "    # Obtener las estadísticas del Pokémon\n",
    "    peso_pokemon = datos_pokemon[\"weight\"]\n",
    "    altura_pokemon = datos_pokemon[\"height\"]\n",
    "    movimientos_pokemon = [movimiento[\"move\"][\"name\"] for movimiento in datos_pokemon[\"moves\"]]\n",
    "    habilidades_pokemon = [habilidad[\"ability\"][\"name\"] for habilidad in datos_pokemon[\"abilities\"]]\n",
    "    tipos_pokemon = [tipo[\"type\"][\"name\"] for tipo in datos_pokemon[\"types\"]]\n",
    "\n",
    "    # Mostrar la información del Pokémon\n",
    "    print(f\"**Nombre:** {datos_pokemon['name'].capitalize()}\")\n",
    "    print(f\"**Imagen:** {imagen_pokemon}\")\n",
    "    print(f\"**Peso:** {peso_pokemon} kg\")\n",
    "    print(f\"**Altura:** {altura_pokemon} m\")\n",
    "    print(\"**Movimientos:**\")\n",
    "    for movimiento in movimientos_pokemon:\n",
    "        print(f\" - {movimiento}\")\n",
    "    print(\"**Habilidades:**\")\n",
    "    for habilidad in habilidades_pokemon:\n",
    "        print(f\" - {habilidad}\")\n",
    "    print(\"**Tipos:**\")\n",
    "    for tipo in tipos_pokemon:\n",
    "        print(f\" - {tipo}\")\n",
    "\n",
    "    # Guardar la información del Pokémon en un archivo .json\n",
    "    with open(f\"pokedex/{nombre_pokemon}.json\", \"w\") as archivo_json:\n",
    "        json.dump({\"nombre\": datos_pokemon[\"name\"], \"imagen\": imagen_pokemon, \"peso\": peso_pokemon, \"altura\": altura_pokemon, \"movimientos\": movimientos_pokemon, \"habilidades\": habilidades_pokemon, \"tipos\": tipos_pokemon}, archivo_json, indent=4)\n",
    "\n",
    "    print(f\"Información del Pokémon guardada en el archivo '{nombre_pokemon}' dentro de la carpeta 'pokedex'.\")\n",
    "else:\n",
    "    print(\"El Pokémon no está registrado en la Pokédex.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0e559395-fb30-4734-95da-7ca32f8101d7",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
